In [149]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score


In [150]:
data = pd.read_csv("weather.nominal.csv")

In [151]:
data

outlook temperature humidity  windy play
0      sunny         hot     high  False   no
1      sunny         hot     high   True   no
2   overcast         hot     high  False  yes
3      rainy        mild     high  False  yes
4      rainy        cool   normal  False  yes
5      rainy        cool   normal   True   no
6   overcast        cool   normal   True  yes
7      sunny        mild     high  False   no
8      sunny        cool   normal  False  yes
9      rainy        mild   normal  False  yes
10     sunny        mild   normal   True  yes
11  overcast        mild     high   True  yes
12  overcast         hot   normal  False  yes
13     rainy        mild     high   True   no

In [152]:
x_play = data.iloc[:,0:4].values
y_play = data.iloc[:,4].values
x_play
# y_play = np.reshape(y_play, (-1, 1))

array([['sunny', 'hot', 'high', False],
       ['sunny', 'hot', 'high', True],
       ['overcast', 'hot', 'high', False],
       ['rainy', 'mild', 'high', False],
       ['rainy', 'cool', 'normal', False],
       ['rainy', 'cool', 'normal', True],
       ['overcast', 'cool', 'normal', True],
       ['sunny', 'mild', 'high', False],
       ['sunny', 'cool', 'normal', False],
       ['rainy', 'mild', 'normal', False],
       ['sunny', 'mild', 'normal', True],
       ['overcast', 'mild', 'high', True],
       ['overcast', 'hot', 'normal', False],
       ['rainy', 'mild', 'high', True]], dtype=object)

In [153]:
from sklearn.preprocessing import LabelEncoder
le_outlook = LabelEncoder()
le_temperature =LabelEncoder()
le_humidity =LabelEncoder()
le_windy =LabelEncoder()
# le_play =LabelEncoder()

In [154]:
x_play[:,0] = le_outlook.fit_transform(x_play[:,0])
x_play[:,1] = le_temperature.fit_transform(x_play[:,1])
x_play[:,2] = le_humidity.fit_transform(x_play[:,2])
x_play[:,3] = le_windy.fit_transform(x_play[:,3])
# y_play[:,0] = le_play.fit_transform(y_play[:,0])
x_play

array([[2, 1, 0, 0],
       [2, 1, 0, 1],
       [0, 1, 0, 0],
       [1, 2, 0, 0],
       [1, 0, 1, 0],
       [1, 0, 1, 1],
       [0, 0, 1, 1],
       [2, 2, 0, 0],
       [2, 0, 1, 0],
       [1, 2, 1, 0],
       [2, 2, 1, 1],
       [0, 2, 0, 1],
       [0, 1, 1, 0],
       [1, 2, 0, 1]], dtype=object)

In [155]:
# xtr,xval,ytr,yval = train_test_split(x_play,y_play,test_size = 0.0, random_state = 0)

In [156]:
from sklearn.ensemble import RandomForestClassifier

In [157]:
arvores = RandomForestClassifier(random_state=0)
arvores.fit(x_play,y_play)
pred = arvores.predict(xval)
arvores.feature_importances_

array([0.44782477, 0.15272202, 0.22406556, 0.17538765])

In [159]:
confusion_matrix(yval,p)

array([[0, 0],
       [1, 2]])

In [158]:
#rainy(1), cool(0), normal(1), true(1)
y_pred = arvores.predict([[1,0,1,1]])
y_pred

array(['no'], dtype=object)